In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("D:/prog/Data_Analyst_Pet_Projects/E-Commerce/data.csv", encoding="ISO-8859-1")

In [4]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [5]:
df.info

<bound method DataFrame.info of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]>

In [6]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

# Analysis of Columns Based on Descriptive Statistics

- `Column 'Quantity'`: Requires filtering of anomalous values (`Quantity < 0` - returns). Check for duplicate rows with the same `InvoiceNo` and `CustomerID` (possible errors).
  
- `Column 'UnitPrice'`: Remove rows with `UnitPrice < 0` (likely errors). Split prices into quantiles and analyze which products are too expensive.

- `Column 'CustomerID'`: Check rows without `CustomerID` (likely anonymous purchases). Find out how customers are distributed by the number of orders.

## Conclusions

  1. Clean the data — remove negative values in `Quantity` and `UnitPrice`.
  2. Analyze returns (`Quantity < 0`).
  3. Handle missing `CustomerID`.
  4. Build graphs to analyze the distribution of `Quantity` and `UnitPrice`.

In [7]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

# Analysis of Column Types

  - `Column 'InvoiceNo'`: Invoice number - the user's order number, type 'object', which needs to be replaced with 'int64', as the column values are integers. Duplicates may exist.
    
  - `Column 'StockCode'`: Stock code, type 'object'. No type change is required. Further checks for duplicates will be performed.
     
  - `Column 'Description'`: Product description, type 'object' is correct.

  - `Column 'Quantity'`: Quantity of a specific product, type 'int64' is correct.

  - `Column 'InvoiceDate'`: Order date, type 'object' is incorrect, it needs to be replaced with 'datetime'..

  - `Column 'UnitPrice'`: Price per unit of the product, type 'float64' is correct.

  - `Column 'CustomerID'`: Unique customer identifier, type 'float64', which is better replaced with 'int64'.

  - `Column 'Country'`: Country of the order, type 'object' is correct.

In [8]:
df[['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']].isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df['InvoiceNo'] = pd.to_numeric(df['InvoiceNo'], errors='coerce').astype('Int64')

In [45]:
df[df['InvoiceNo'].isna()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsReturn
141,<NA>,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom,True
154,<NA>,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom,True
235,<NA>,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom,True
236,<NA>,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,True
237,<NA>,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,True
...,...,...,...,...,...,...,...,...,...
540449,<NA>,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom,True
541541,<NA>,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom,True
541715,<NA>,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom,True
541716,<NA>,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom,True
541717,<NA>,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom,True

In [11]:
df[df['StockCode'].isin(df[df['InvoiceNo'].isna()]['StockCode'].unique())] # understand which products are most frequently returned

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [12]:
returns_df = df[df['Quantity'] < 0] # extract returns into a separate dataframe (for analysis)

In [13]:
top_returns = returns_df.groupby('StockCode').agg({'Quantity': 'sum'}).reset_index() # aggregation by StockCode to calculate the number of returns

In [14]:
top_returns_sorted = top_returns.sort_values(by='Quantity', ascending=False) # sort by number of returns

In [15]:
top_returns_sorted.head(10)

     StockCode  Quantity
2273    84964B        -1
2043     84006        -1
1783    35598D        -1
445      21594        -1
1528     23180        -1
620      21910        -1
2353     85065        -1
1513     23164        -1
1501     23150        -1
1839    37444C        -1

In [16]:
df['IsReturn'] = df['InvoiceNo'].isna()

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

In [24]:
df['CustomerID'] = df['CustomerID'].astype(str)

In [36]:
df.loc[:, 'CustomerID'] = df['CustomerID'].fillna('Guest')

In [42]:
df[df['UnitPrice'] < 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, IsReturn]
Index: []

In [38]:
df = df[df['UnitPrice'] >= 0]

In [39]:
df['Description'].isna().sum()

0

In [40]:
df.loc[:, 'Description'] = df['Description'].fillna('Unknown')

In [41]:
df['Description'].isna().sum()

0

In [43]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsReturn
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,False
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,False
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,False
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,False
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,False
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,False

In [47]:
df['InvoiceDate'].isna().sum()

0

In [50]:
df['InvoiceNo'].isna().sum()

0

In [56]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
IsReturn       0
dtype: int64

In [58]:
df[df['Quantity'] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsReturn
2406,536589,21777,Unknown,-10,2010-12-01 16:50:00,0.0,<NA>,United Kingdom,False
4347,536764,84952C,Unknown,-38,2010-12-02 14:42:00,0.0,<NA>,United Kingdom,False
7188,536996,22712,Unknown,-20,2010-12-03 15:30:00,0.0,<NA>,United Kingdom,False
7189,536997,22028,Unknown,-20,2010-12-03 15:30:00,0.0,<NA>,United Kingdom,False
7190,536998,85067,Unknown,-6,2010-12-03 15:30:00,0.0,<NA>,United Kingdom,False
...,...,...,...,...,...,...,...,...,...
535333,581210,23395,check,-26,2011-12-07 18:36:00,0.0,<NA>,United Kingdom,False
535335,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,<NA>,United Kingdom,False
535336,581213,22576,check,-30,2011-12-07 18:38:00,0.0,<NA>,United Kingdom,False
536908,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,<NA>,United Kingdom,False
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,<NA>,United Kingdom,False

# Conclusions

  1. Handling missing values:
     - Missing values in columns were handled using the `fillna()` method. For the `Description` column, missing values were replaced with `'Unknown'`.
     - For the `CustomerID` column, missing values have been replaced with the string `'Guest'`.
     - In the InvoiceNo column, missing or invalid values were cast to `Int64` using `pd.to_numeric()` and then treated as blanks (`NaN`) if they could not be converted to a numeric value.
       
  2. Data type conversion:
     - The `InvoiceNo` column was converted to a numeric data type (`Int64`) using `pd.to_numeric()`, where invalid values were replaced with NaN.
     - The `InvoiceDate` column has been converted to type `datetime` to work correctly with dates.
     - The `CustomerID` column has been converted to a string type to avoid errors when handling gaps.
       
  3. Filtering and analyzing returns:
     - A new `DataFrame returns_df` is created containing only those rows where `Quantity < 0`, which corresponds to product returns.
     - To analyze returns, the `StockCode` column was aggregated to calculate the number of returns for each product. The results were sorted by descending number of returns.
     - The products that were most frequently returned (by the `StockCode` column) were found.
  4. Working with products with negative price:

     - An analysis was performed of items with a negative price (`UnitPrice < 0`), which are likely to be erroneous entries or returns.
     - These rows were removed from the main dataset by filtering `df['UnitPrice'] >= 0`.
  5. Check for missing values:
     - After all manipulations with the data, a final check for missing values in the columns was performed. There were no gaps left in any of the columns, which is confirmed by the output of `df.isna().sum()`, where all values are 0.

## Results
- All missing values were processed.
- Incorrect and unnecessary data has been removed or corrected.
- A returns analysis was performed and the most frequently returned products were identified.
- The data was converted to the required types for further analysis.

# Analysis plan

1. General sales characteristics:
    - What products are sold most frequently (by quantity)?
    - Which products have the highest revenue (by total value)?
    - How are sales distributed across countries?

2. Returns analysis:
    - What products were most frequently returned?
    - Is there a relationship between the number of returns and the price of a product?
    - Which countries or customers make the most returns?
    
3. Customers and purchasing behavior:
    - How many unique customers made purchases?
    - Which customers (by ID) buy the most?

In [74]:
top_selling_products = df.groupby('StockCode').agg({'Quantity': 'sum'}).reset_index() # group by 'StockCode' and sum 'Quantity' to calculate sales

In [82]:
top_selling_products = top_selling_products.merge(df[['StockCode', 'Description']].drop_duplicates(), on='StockCode', how='left') # add product description from source DataFrame

In [80]:
top_selling_products_sorted = top_selling_products.sort_values(by='Quantity', ascending=False)

In [81]:
top_selling_products_sorted.head(10)

     StockCode  Quantity                         Description
3517     23843     80995         PAPER CRAFT , LITTLE BIRDIE
2929     23166     78033      MEDIUM CERAMIC TOP STORAGE JAR
1693     22197     56921                      POPCORN HOLDER
1692     22197     56921                SMALL POPCORN HOLDER
4276     84077     55047   WORLD WAR 2 GLIDERS ASSTD DESIGNS
5054    85099B     48478             JUMBO BAG RED RETROSPOT
5086    85123A     41408         wrongly marked carton 22804
5085    85123A     41408                                   ?
5084    85123A     41408  WHITE HANGING HEART T-LIGHT HOLDER
5087    85123A     41408  CREAM HANGING HEART T-LIGHT HOLDER