In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("D:/prog/Data_Analyst_Pet_Projects/E-Commerce/data.csv", encoding="ISO-8859-1")

In [6]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [8]:
df.info

<bound method DataFrame.info of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]>

In [9]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

# Анализ стобцов на основе описательной статистики

- `Столб 'Quantity'`: Требуется фильтрация аномальных значений (`Quantity < 0` - возврат). Проверить, есть ли дубликаты строк с одинаковыми `InvoiceNo` и `CustomerID` (возможны ошибки).
  
- `Столб 'UnitPrice'`: Удалить строки с `UnitPrice < 0` (скорее всего, ошибки). Разбить цены по квантилям и проанализировать, какие товары слишком дорогие.

- `Столб 'CustomerID'`: Проверить строки без CustomerID (скорее всего, анонимные покупки). Узнать как распределены клиенты по числу заказов (есть ли лояльные клиенты).

## Выводы

  1. Очистить данные — убрать отрицательные значения `Quantity` и `UnitPrice`.
  2. Проанализировать возвраты (`Quantity < 0`).
  3. Обработать пропущенные `CustomerID` — если возможно, попытаться восстановить их (например, по `InvoiceNo`).
  4. Построить графики для анализа распределения `Quantity` и `UnitPrice`.

In [7]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

# Анализ типов столбцов:

  - `Столб 'InvoiceNo'`: Номер счёта - номер заказа пользователя, тип - 'object', который нужно заменить на 'int64', так как значения столбца целочисленное. Дубликаты возможны
    
  - `Столб 'StockCode'`: Фондовый код, значение типа 'object'. Смена типа не требуется. В дальшейшем будет проведена проверка на дубликаты.
     
  - `Столб 'Description'`: Описание товара, тип 'object' является корректным.

  - `Столб 'Quantity'`: Количество определённого товара, тип 'int64' является корректным.

  - `Столб 'InvoiceData'`: Дата заказа, тип 'object' является некорректным, нужна замена типа на 'datetime'.

  - `Столб 'UnitPrice'`: Цена за единицу товара, тип 'float64' является корректным.

  - `Столб 'CustomerID'`: Уникальный идентификатор покупателя, тип 'float64', который лучше заменить на 'int64'.

  - `Столб 'Country'`: Страна заказа, тип 'object' являеся корректным.